# Guarantee that every request redirects to '/'

GET {{HostAddress}}

###

POST {{HostAddress}}

###

PATCH {{HostAddress}}

###

DELETE {{HostAddress}}

###

POST {{HostAddress}}/somegibberishinformation/anothergibberishinformation

###

POST {{HostAddress}}/checkuserexists
Content-Type: application/json

{
    "username": "testuser"
}
