// Descomente a linha abaixo caso não tenha o arquivo http-client.env.json configurado
// @HostAddress= http://localhost:8080

### GetMain
// Deve retornar 200 e html
GET {{HostAddress}}

### PostMain
// Deve retornar 200 e html
POST {{HostAddress}}

### PatchMain
// Deve retornar 302 Found - Redirecting to /
PATCH {{HostAddress}}

### DeleteMain
// Deve retornar 200 e html
DELETE {{HostAddress}}

### PostToRandomRoute
// Deve retornar 200 e html
POST {{HostAddress}}/somegibberishinformation/anothergibberishinformation

### PostUserCheckNotValid
// Deve retornar 400 - não é nome válido
POST {{HostAddress}}/usercheck
Content-Type: application/json

{
    "username": "shit"
}

### PostUserCheck
// Deve retornar 204 caso não exista um usuário com o nome logado
// Deve retornar 403 caso exista um usuário com o nome logado
POST {{HostAddress}}/usercheck
Content-Type: application/json

{
    "username": "iugmali"
}
